export const enum Identifiers {
	ArgsMissing = 'argsMissing',
	ArgsUnavailable = 'argsUnavailable',

	ArgumentBooleanError = 'booleanError',
	ArgumentChannelError = 'channelError',
	ArgumentDateError = 'dateError',
	ArgumentDateTooEarly = 'dateTooEarly',
	ArgumentDateTooFar = 'dateTooFar',
	ArgumentFloatError = 'floatError',
	ArgumentFloatTooLarge = 'floatTooLarge',
	ArgumentFloatTooSmall = 'floatTooSmall',
	ArgumentHyperlinkError = 'hyperlinkError',
	ArgumentIntegerError = 'integerError',
	ArgumentIntegerTooLarge = 'integerTooLarge',
	ArgumentIntegerTooSmall = 'integerTooSmall',
	ArgumentMemberError = 'memberError',
	ArgumentMemberMissingGuild = 'memberMissingGuild',
	ArgumentMessageError = 'messageError',
	ArgumentNumberError = 'numberError',
	ArgumentNumberTooLarge = 'numberTooLarge',
	ArgumentNumberTooSmall = 'numberTooSmall',
	ArgumentRoleError = 'roleError',
	ArgumentRoleMissingGuild = 'roleMissingGuild',
	ArgumentStringTooLong = 'stringTooLong',
	ArgumentStringTooShort = 'stringTooShort',
	ArgumentUserError = 'userError',
	ArgumentEnumEmptyError = 'enumEmptyError',
	ArgumentEnumError = 'enumError',

	CommandDisabled = 'commandDisabled',

  PreconditionGroupOnly = 'preconditionGroupOnly',
  PreconditionPrivateOnly = 'preconditionPrivateOnly'
}
